### ISSUE TITLE
New rules: Layout/TrailingCommaInHashLiteral (also ...InArrayLiteral)

### ISSUE THREAD

**Issue by NJRBailey** [qmee/dev-public-utils#10]
```yaml
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
```
This could be controversial - it's a rule the UX team use that Fabian introduced. At first Chris and I were against it but I have come to love it :joy: 

It means that multiline hashes and arrays always have a trailing comma. It makes adding and editing easier and doesn't affect readability in my opinion.

From this:
```ruby
{
  a: "a",
  b: "b"
}
```
to this:
```ruby
{
  a: "a",
  b: "b",
}
```
