### ISSUE TITLE
New rules: Style/FirstMethodArgumentLineBreak and Layout/MultilineMethodParameterLineBreaks

### ISSUE THREAD

**Issue by NJRBailey** [qmee/dev-public-utils#21]
```yaml
Style/FirstMethodArgumentLineBreak:
  Enabled: true

Layout/MultilineMethodParameterLineBreaks:
  Enabled: true
```
These rules force multiline arguments to be on separate lines, from this:
```ruby
call(p1,
  p2, p3
)
```
to this:
```ruby
call(p1, p2, p3)
```
OR this:
```ruby
call(
  p1,
  p2,
  p3,
)
```
The only downside (imo) is that multiline hashes are also pushed onto their own line like this:
from:
```ruby
call({
  a: 1,
  b: 2,
})
```
to:
```ruby
call(
  {
    a: 1,
    b: 2,
  }
)
```
